### ISSUE TITLE
Empty scraper popup

### ISSUE THREAD

**Issue by mnmldave** [mnmldave/scraper#1]
Sometimes, after choosing "Scrape selected...", the popup is empty except for the vertical splitter bar. Refreshing the popup (with cmd-r) usually restores things to expected state.

**Comment by mnmldave** [comment]
Can't reproduce and haven't seen it lately, so closing for now.

**Comment by mnmldave** [comment]
Started happening frequently in Windows while testing, so reopened.

Seems to be due to layout plugin, as the left/right panes have styles with `display:none` for some reason. As workaround, resizing the content after short period after document loads.

**Comment by mnmldave** [comment]
Adding workaround that resizes content shortly after document loads. Hopefully closed by 0623f13a9693c05336f84502f86f4f0a2c7dc3b2.

**Comment by jdoliner** [comment]
This issue still pops up under Xmonad. I'm guessing this has something to do with xmonad not allowing resizing windows.
