### ISSUE TITLE
Can't export secure websites

### ISSUE THREAD

**Issue by tordek111** [mnmldave/scraper#10]
I am able to scrape the website no problem (it does exactly what i need it to do) but when trying to export the data to docs, the export window flashes for about 3 seconds and nothing happens.  When i go into docs there is nothing there. 

All other scrapes and webpages work just fine for the export except this secure site. 

The site i am trying to export is here ; http://express.sputnik.com/sne/express/00212988cd18/usage

Dave, if you want to duplicate the issue, feel free to messgage me and i can provide you the password.  Don't really want to drop it here on the public realm. 

Thanks

**Comment by mnmldave** [comment]
Seems to be directly related to [this thread](http://www.google.com/support/forum/p/apps-apis/thread?tid=123b95abde111505&hl=en) so will workaround and encode slug (the spreadsheet title) appropriately.

**Comment by tordek111** [comment]
Awesome Dave.  Very impressed on your turn around time. 

Appreciate it very much.

**Comment by mnmldave** [comment]
Encoding google spreadsheet slug and stripping trailing colon as workaround for bug. Closed by 45ff0f7236d16cd48b58ddf52d602b38874033d8.
Sending more verbose errors when export fails.
