### ISSUE TITLE
Export to Google Docs is faulty

### ISSUE THREAD

**Issue by pcomans** [mnmldave/scraper#6]
The fields in the Google Docs spreadsheet are not filled correctly.
How to reproduce this bug:
1. Go to http://www.dcresource.com/reviews/canon/powershot_sx30-review
2. Mark everything in the table and click Scrape similar...
3. Observe that the columns for the feature LCD size / resolution and EVF size / resolution are filled correctly
4. Export to Google Docs
5. You should see that the columns mentioned above are filled incorrectly

My guess would be that the quote signs " are not escaped correctly upon export.

**Comment by mnmldave** [comment]
Ah you're right. That's particularly embarrassing :) I've published the fix to version 1.3 which should be out now.
